---
- name: Ensure configs directory exists for bunker
  ansible.builtin.file:
    path: "{{ bunker_service_home }}/.config/containers/systemd/configs"
    state: directory
    owner: "{{ bunker_service_user }}"
    group: "{{ bunker_service_user }}"
    mode: "0755"

- name: Deploy Bunkerweb environment files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ bunker_service_home }}/.config/containers/systemd/configs/{{ item }}"
    owner: "{{ bunker_service_user }}"
    group: "{{ bunker_service_user }}"
    mode: "0600"
  loop:
    - bunkerized_nginx.env
    - json_analytics.env
